server:
  port: 8090

spring:
  thymeleaf:
    prefix: classpath:/templates/

  datasource:
    url: jdbc:mysql://localhost:3306/library?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=GMT%2B8
    username: fisco
    password: '!123456FISCOfisco'
    driver-class-name: com.mysql.cj.jdbc.Driver
