spring:
  datasource:
    url: jdbc:mysql://localhost:3306/medical_resource?serverTimezone=Asia/Shanghai&characterEncoding=UTF-8
    username: username
    password: password
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 10000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM user
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      connection-properties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
  redis:
    port: 6379
    host: 127.0.0.1
    pool:
      max-active: 20
      max-wait: -1
      max-idle: 10
      min-idle: 5
      timeout: 0
    database: 0
  mail:
    username: mail@mail.com
    password: password
    host: mail_host
    properties:
      mail:
        smtp:
          port: 587
          auth: true
          starttls:
            enable: true
            required: true
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    encoding: UTF-8
    servlet:
      content-type: text/html
    mode: HTML5
    check-template-location: true
  jackson:
    time-zone: Asia/Shanghai

mybatis:
  configuration:
    cache-enabled: true
  mapper-locations: classpath:mapper/*.xml

jwt:
  token-secret: token-secret

server:
  port: 45000

static:
  contract-address: "contract-address"
  contract-owner-private-key: "53783c2cf5cd758b896433d6d901b44b4e51d3af0984de46164758dcbf553789"


